<?php
// logo_head.php - Shared HTML head tags: favicon, meta description, OG/Twitter cards
// HOW TO USE: Set $page_description before including this file for a custom Google snippet.
// Include with include() not include_once() to ensure it renders on every page.

// db.php / logo_helper.php are safe to call multiple times (they guard with isset)
if (!function_exists('get_custom_logo_url')) {
    require_once __DIR__ . '/logo_helper.php';
}

// ── Compute the subdirectory base path ────────────────────────────────────────
// The app lives in /GHR/a1/ on this server. All favicon/asset URLs must be
// root-relative so they work regardless of which PHP page is currently loaded.
$_lh_base = '';
$_lh_script = str_replace('\\', '/', $_SERVER['SCRIPT_NAME'] ?? '');
// Strip the filename to get the directory, e.g. /GHR/a1/
$_lh_base = rtrim(dirname($_lh_script), '/') . '/';

// ── Active logo URL (relative to project root, e.g. "uploads/logo/logo_123.png") ──
$_lh_logo_rel  = get_custom_logo_url();           // e.g. "uploads/logo/logo_123.png"
$_lh_favicon   = $_lh_base . $_lh_logo_rel;      // e.g. "/GHR/a1/uploads/logo/logo_123.png"

// ── Absolute URL for OG/Twitter (needs full https://…) ────────────────────────
$_lh_protocol  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$_lh_host      = $_SERVER['HTTP_HOST'] ?? 'localhost';
$_lh_logo_abs  = $_lh_protocol . '://' . $_lh_host . $_lh_favicon;

// ── Page meta description ─────────────────────────────────────────────────────
if (!isset($page_description) || trim($page_description) === '') {
    $page_description = 'ArenaReserve – Book sports grounds instantly. Find and reserve cricket, football, and multi-sport venues near you. Trusted by players and ground owners across Pakistan.';
}
$_lh_desc = htmlspecialchars(trim($page_description), ENT_QUOTES, 'UTF-8');
?>
<!-- ═══════════════════════════════════════════════════
     ArenaReserve – SEO & Favicon Head Tags
     Generated by logo_head.php
═══════════════════════════════════════════════════ -->

<!-- Meta Description (Google Search 2-line snippet) -->
<meta name="description" content="<?php echo $_lh_desc; ?>">
<meta name="robots" content="index, follow">

<!-- Favicon / Site Icon (root-relative paths — works in any subdirectory) -->
<link rel="icon" type="image/png" href="<?php echo htmlspecialchars($_lh_favicon); ?>">
<link rel="shortcut icon" href="<?php echo htmlspecialchars($_lh_favicon); ?>">
<link rel="apple-touch-icon" href="<?php echo htmlspecialchars($_lh_favicon); ?>">

<!-- Open Graph (Facebook / LinkedIn) -->
<meta property="og:site_name" content="ArenaReserve">
<meta property="og:description" content="<?php echo $_lh_desc; ?>">
<meta property="og:image" content="<?php echo htmlspecialchars($_lh_logo_abs); ?>">
<meta property="og:image:secure_url" content="<?php echo htmlspecialchars($_lh_logo_abs); ?>">
<meta property="og:image:width" content="512">
<meta property="og:image:height" content="512">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary">
<meta name="twitter:description" content="<?php echo $_lh_desc; ?>">
<meta name="twitter:image" content="<?php echo htmlspecialchars($_lh_logo_abs); ?>">
